import type { MetricDefinition } from "@myfinance/domain";

export const metricRegistry: MetricDefinition[] = [
  {
    metricId: "net_worth_current",
    displayName: "Net Worth",
    description: "Latest cash plus latest portfolio market value, excluding double-counting of securities as cash.",
    metricClass: "current_value",
    unitType: "currency",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope"],
    sourceQueryOrView: "public.mv_dashboard_current",
    defaultComparison: "latest prior month-end snapshot",
    explanationQuery: "public.v_current_portfolio_valuation",
    freshnessPolicy: "refresh after imports, edits, positions, and prices",
    displayHints: { card: "primary", group: "homepage" },
  },
  {
    metricId: "cash_total_current",
    displayName: "Cash",
    description: "Latest statement or computed cash balances across cash accounts and brokerage cash.",
    metricClass: "current_value",
    unitType: "currency",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope"],
    sourceQueryOrView: "public.v_latest_balance_by_account",
    defaultComparison: "latest prior month-end snapshot",
    explanationQuery: "public.v_latest_balance_by_account",
    freshnessPolicy: "refresh after imports and nightly snapshots",
    displayHints: { card: "primary", group: "homepage" },
  },
  {
    metricId: "income_mtd_total",
    displayName: "Income MTD",
    description: "Economic-entity income, dividends, and interest in the selected month-to-date period.",
    metricClass: "flow",
    unitType: "currency",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope", "period"],
    sourceQueryOrView: "public.mv_monthly_income_totals",
    defaultComparison: "same day-count previous month",
    explanationQuery: "public.v_transaction_analytics",
    freshnessPolicy: "refresh after imports and edits",
    displayHints: { card: "primary", group: "homepage" },
  },
  {
    metricId: "spending_mtd_total",
    displayName: "Spending MTD",
    description: "Absolute EUR spending and fees less refunds for the selected period.",
    metricClass: "flow",
    unitType: "currency",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope", "period", "category"],
    sourceQueryOrView: "public.mv_monthly_spending_totals",
    defaultComparison: "same day-count previous month",
    explanationQuery: "public.v_transaction_analytics",
    freshnessPolicy: "refresh after imports and edits",
    displayHints: { card: "primary", group: "homepage" },
  },
  {
    metricId: "operating_net_cash_flow_mtd",
    displayName: "Operating Net Cash Flow MTD",
    description: "Income MTD minus spending MTD.",
    metricClass: "flow",
    unitType: "currency",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope", "period"],
    sourceQueryOrView: "public.mv_dashboard_current",
    defaultComparison: "same day-count previous month",
    explanationQuery: "public.mv_monthly_income_totals",
    freshnessPolicy: "refresh after imports and edits",
    displayHints: { card: "primary", group: "homepage" },
  },
  {
    metricId: "portfolio_market_value_current",
    displayName: "Portfolio Value",
    description: "Current open-position market value converted to EUR, excluding brokerage cash.",
    metricClass: "current_value",
    unitType: "currency",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope"],
    sourceQueryOrView: "public.v_current_portfolio_valuation",
    defaultComparison: "latest prior month-end snapshot",
    explanationQuery: "public.mv_latest_holdings_summary",
    freshnessPolicy: "refresh after price updates and position rebuilds",
    displayHints: { card: "primary", group: "homepage" },
  },
  {
    metricId: "portfolio_unrealized_pnl_current",
    displayName: "Unrealized Gain",
    description: "Current open-position market value minus open cost basis.",
    metricClass: "current_value",
    unitType: "currency",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope"],
    sourceQueryOrView: "public.v_current_portfolio_valuation",
    defaultComparison: "latest prior month-end snapshot",
    explanationQuery: "public.mv_latest_holdings_summary",
    freshnessPolicy: "refresh after price updates and position rebuilds",
    displayHints: { card: "primary", group: "homepage" },
  },
  {
    metricId: "pending_review_count",
    displayName: "Pending Review",
    description: "Rows that still require operator review.",
    metricClass: "quality",
    unitType: "count",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope"],
    sourceQueryOrView: "public.v_transaction_analytics",
    defaultComparison: "latest value",
    explanationQuery: "public.v_transaction_analytics",
    freshnessPolicy: "refresh after classification and edits",
    displayHints: { banner: true },
  },
  {
    metricId: "unclassified_amount_mtd",
    displayName: "Unclassified Amount MTD",
    description: "Absolute current-month uncategorized spend requiring attention.",
    metricClass: "quality",
    unitType: "currency",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope", "period"],
    sourceQueryOrView: "public.v_transaction_analytics",
    defaultComparison: "latest value",
    explanationQuery: "public.v_transaction_analytics",
    freshnessPolicy: "refresh after classification and edits",
    displayHints: { banner: true },
  },
  {
    metricId: "stale_accounts_count",
    displayName: "Stale Accounts",
    description: "Accounts whose latest import is older than their configured threshold.",
    metricClass: "quality",
    unitType: "count",
    supportedScopes: ["consolidated", "entity", "account"],
    supportedFilters: ["scope"],
    sourceQueryOrView: "public.v_latest_balance_by_account",
    defaultComparison: "latest value",
    explanationQuery: "public.v_latest_balance_by_account",
    freshnessPolicy: "refresh after imports and nightly snapshots",
    displayHints: { banner: true },
  },
];
