#!/usr/bin/env python3
"""Read the current MyFinanceApp workspace metadata and print it as JSON."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


DISCOVERY_SCRIPT = r"""
import { createFinanceRepository } from "@myfinance/db";
import { metricRegistry } from "@myfinance/analytics";
import { accountTypeOptions, canonicalFieldKeys, signModeOptions } from "@myfinance/domain";

const repository = createFinanceRepository();
const dataset = await repository.getDataset();
const entityById = new Map(dataset.entities.map((entity) => [entity.id, entity]));

const payload = {
  workspace: process.env.MYFINANCE_WORKSPACE_ROOT ?? process.cwd(),
  generatedAt: new Date().toISOString(),
  profile: dataset.profile
    ? {
        id: dataset.profile.id,
        email: dataset.profile.email,
        displayName: dataset.profile.displayName,
        defaultBaseCurrency: dataset.profile.defaultBaseCurrency,
        timezone: dataset.profile.timezone,
      }
    : null,
  scopeExamples: [
    "consolidated",
    ...dataset.entities.map((entity) => entity.slug),
    ...dataset.accounts.map((account) => `account:${account.id}`),
  ],
  entities: dataset.entities.map((entity) => ({
    id: entity.id,
    slug: entity.slug,
    displayName: entity.displayName,
    entityKind: entity.entityKind,
    baseCurrency: entity.baseCurrency,
    active: entity.active,
  })),
  accounts: dataset.accounts.map((account) => ({
    id: account.id,
    entityId: account.entityId,
    entitySlug: entityById.get(account.entityId)?.slug ?? null,
    institutionName: account.institutionName,
    displayName: account.displayName,
    accountType: account.accountType,
    assetDomain: account.assetDomain,
    defaultCurrency: account.defaultCurrency,
    includeInConsolidation: account.includeInConsolidation,
    isActive: account.isActive,
    importTemplateDefaultId: account.importTemplateDefaultId,
    lastImportedAt: account.lastImportedAt,
  })),
  templates: dataset.templates.map((template) => ({
    id: template.id,
    name: template.name,
    institutionName: template.institutionName,
    compatibleAccountType: template.compatibleAccountType,
    fileKind: template.fileKind,
    defaultCurrency: template.defaultCurrency,
    active: template.active,
    version: template.version,
  })),
  rules: dataset.rules.map((rule) => ({
    id: rule.id,
    priority: rule.priority,
    active: rule.active,
    autoGenerated: rule.autoGenerated,
    createdFromTransactionId: rule.createdFromTransactionId,
    hitCount: rule.hitCount,
  })),
  securities: dataset.securities.map((security) => ({
    id: security.id,
    displaySymbol: security.displaySymbol,
    providerSymbol: security.providerSymbol,
    canonicalSymbol: security.canonicalSymbol,
    name: security.name,
    assetType: security.assetType,
    quoteCurrency: security.quoteCurrency,
    isin: security.isin,
    providerName: security.providerName,
    active: security.active,
    lastPriceRefreshAt: security.lastPriceRefreshAt,
  })),
  metricIds: metricRegistry.map((metric) => ({
    metricId: metric.metricId,
    displayName: metric.displayName,
    unitType: metric.unitType,
    supportedScopes: metric.supportedScopes,
    supportedFilters: metric.supportedFilters,
  })),
  supportedValues: {
    accountTypes: [...accountTypeOptions],
    signModes: [...signModeOptions],
    canonicalFieldKeys: [...canonicalFieldKeys],
  },
};

console.log(JSON.stringify(payload, null, 2));
"""


def find_workspace(start: Path) -> Path | None:
    for candidate in (start, *start.parents):
        if (candidate / "apps/cli/src/index.ts").exists() and (candidate / "package.json").exists():
            return candidate
    return None


def resolve_workspace(raw_workspace: str | None) -> Path:
    if raw_workspace:
        workspace = Path(raw_workspace).expanduser().resolve()
        if not (workspace / "apps/cli/src/index.ts").exists():
            raise SystemExit(f"Workspace does not look like MyFinanceApp: {workspace}")
        return workspace

    workspace = find_workspace(Path.cwd().resolve())
    if workspace is None:
        raise SystemExit(
            "Could not find a MyFinanceApp workspace from the current directory. "
            "Pass --workspace /path/to/MyFinanceApp."
        )
    return workspace


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Inspect the current MyFinanceApp dataset and supported values.",
    )
    parser.add_argument(
        "--workspace",
        help="Path to the MyFinanceApp repository root. Defaults to the nearest matching ancestor.",
    )
    parser.add_argument(
        "--show-command",
        action="store_true",
        help="Print the raw command used for discovery to stderr before executing it.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    workspace = resolve_workspace(args.workspace)
    command = [
        "pnpm",
        "--dir",
        str(workspace),
        "--filter",
        "@myfinance/cli",
        "exec",
        "node",
        "--input-type=module",
        "--import",
        "tsx",
        "-e",
        DISCOVERY_SCRIPT,
    ]

    if args.show_command:
        print("Forwarding:", " ".join(command), file=sys.stderr)

    env = dict(os.environ, MYFINANCE_WORKSPACE_ROOT=str(workspace))
    completed = subprocess.run(command, cwd=workspace, env=env)
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
